import platform
import os
import json
import re

import sublime
import sublime_plugin

import NeoVintageous.dep.json5kit as json5kit # noqa: F401,F403
from NeoVintageous.dep.json5kit     	import Json5Node, Json5Array, Json5String # noqa: F401,F403
from NeoVintageous.nv.layout_convert	import lyt, LayoutConverter

__all__ = [
  'NvUserKeymap'
]


def convertKeymapLayout(keymap, lyt_from, lyt_to):
  lyt_converter   = LayoutConverter()
  keymap_tree = json5kit.parse(keymap)

  reSp = re.compile(r'\s')
  reSingleKey = re.compile(r"""
    (?P<pre>    ^[\s]*)   #
    (?P<keycap> [^\s])    # ←
    (?P<pos>     [\s]*$)  #
    """, re.X)
  reLastKey = re.compile(r"""
    (?P<pre>    ^.*\+[\s]*) # up to and including the last +
    (?P<keycap> [^\s])      # ←
    (?P<pos>    [\s]*$)     #
    """, re.X)
  class ArrayKeyComboTransformer(json5kit.Json5Transformer):
    def visit_String(self, node):
      key_combo_raw = node.value  # 'ctrl + a '
      if   (reM := re.match(reSingleKey, key_combo_raw)):
        if (keycap := reM.group('keycap')):
          keycap_new   	= (lyt_converter.convert(keycap, lyt_from, lyt_to)).replace('\\','\\\\')
          key_combo_new	= re.sub(reSingleKey, fr"\g<pre>{keycap_new}\g<pos>",key_combo_raw)
          return node.replace(json.dumps(key_combo_new, ensure_ascii=False))
        else:
          return node
      elif (reM := re.match(reLastKey  , key_combo_raw)):
        if (keycap := reM.group('keycap')):
          keycap_new   	= (lyt_converter.convert(keycap, lyt_from, lyt_to)).replace('\\','\\\\')
          key_combo_new	= re.sub(reLastKey  , fr"\g<pre>{keycap_new}\g<pos>",key_combo_raw)
          return node.replace(json.dumps(key_combo_new, ensure_ascii=False))
        else:
          return node
      else:
        return node
  class DictTransformer(json5kit.Json5Transformer):
    def __init__(self):
      self.object_value_to_key = {}
    def visit_Object(self, node):
      for key, value in zip(node.keys, node.values):
        self.object_value_to_key[value] = key
      super().generic_visit(node)
      return node

    def generic_visit(self, node):
      super().generic_visit(node)
      key = self.object_value_to_key.get(node)
      if key is None:
        return node
      if key.value.value == "keys":
        if isinstance(node, Json5Array):
          ArrayKeyComboTransformer().visit(node)
        return node
      else:
        return node
  DictTransformer().visit(keymap_tree)
  return keymap_tree.to_source()

class NvUserKeymap(sublime_plugin.ApplicationCommand):
  def __init__(self):
    self.nv_name  	= "NeoVintageous"
    self.nv_keymap	= "Default.sublime-keymap"
    self.dest     	= "$packages/User/NeoVintageous/Default ($platform).sublime-keymap"
    self.cmd      	= "NeoVintageous: Generate non-QWERTY key bindings"

  def run(self, **kwargs):
    nv_keymap_path	= f"Packages/{self.nv_name}/{self.nv_keymap}"
    dest          	= expand(kwargs.get('file', self.dest))
    try:
      nv_keymap_raw = sublime.load_resource(nv_keymap_path) # works, string
    except FileNotFoundError as e:
      sublime.error_message(f"NeoVintageous:\nTried and failed to load\n{nv_keymap_path}")
      return
    try:
      nv_keymap = sublime.decode_value(nv_keymap_raw)
    except ValueError as e:
      sublime.error_message(f"Tried and failed to decode {nv_keymap_path}")
      return
    nv_keymap_user = convertKeymapLayout(nv_keymap_raw, lyt.qwerty, lyt.user)

    try:
      with open(dest, 'w') as file:
        print(f"// Autogenerated via '{self.cmd}' command from '{nv_keymap_path}', changes will be overwritten", file=file)
        print(nv_keymap_user, file=file)
        sublime.message_dialog(f"Key bindings updated at '{dest}'\n\nBUT they override\n  'User/Default.sublime-keymap'\n\nTo override the override place your keymap in subfolder with a name starting with a letter after 'N', e.g.,\n'User/zKeymap'")
    except FileNotFoundError as e:
      sublime.error_message(f"NeoVintageous:\nTried and failed to save generated keymap to\n{dest}")
      return

def expand(string):
  return sublime.expand_variables(string, sublime.active_window().extract_variables())
